version: '3'

env:
  DB_NAME: alc-dict
  CONTAINER_NAME: api

tasks:
  build:
    cmd: docker compose build --no-cache

  up:
    cmd: docker compose up -d

  build.up:
    cmd: docker compose up -d --build

  seed:
    cmd: docker compose exec $CONTAINER_NAME wrangler d1 migrations apply $DB_NAME

  seed.local:
    cmd: docker compose exec $CONTAINER_NAME wrangler d1 migrations apply $DB_NAME --local

  stop:
    cmd: docker compose stop

  down:
    cmd: docker compose down --rmi all --volumes --remove-orphans
