version: '3'

env:
  DB_NAME: alc-dict
  CONTAINER_NAME: api

tasks:
  build:
    cmd: docker compose build --no-cache

  up:
    cmd: docker compose up -d

  build.up:
    cmd: docker compose up -d --build

  seed:
    cmds:
      - docker compose exec $CONTAINER_NAME wrangler d1 execute $DB_NAME --file=./sql/schema.sql
      - docker compose exec $CONTAINER_NAME wrangler d1 migrations apply $DB_NAME

  seed.local:
    cmds:
      - docker compose exec $CONTAINER_NAME wrangler d1 execute $DB_NAME --local --file=./sql/schema.sql
      - docker compose exec $CONTAINER_NAME wrangler d1 migrations apply $DB_NAME --local

  make.migration:
    cmd: docker compose exec $CONTAINER_NAME npx drizzle-kit generate:sqlite

  lint:
    cmds:
      - docker compose exec $CONTAINER_NAME npx prettier . --write
      - docker compose exec $CONTAINER_NAME npx eslint './src/**' --fix

  stop:
    cmd: docker compose stop

  down:
    cmd: docker compose down --rmi all --volumes --remove-orphans
