version: '3'

env:
  APP_NAME: alc-dict
dotenv: ['.env']

tasks:
  build:
    cmds:
      - docker compose build --no-cache

  up:
    cmds:
      - docker compose up -d
    silent: true
  
  build.up:
    cmds:
      - docker compose up -d --build
    silent: true

  seed.local:
    cmd: docker compose exec api wrangler d1 execute alc-dict --file=./sql/schema.sql --local

  stop:
    cmds:
      - docker compose stop

  down:
    cmds:
      - docker compose down --rmi all --volumes --remove-orphans
