version: '3'

env:
  DB_NAME: alc-dict
  CONTAINER_NAME: api

tasks:
  build:
    cmd: docker compose build --no-cache

  up:
    cmd: docker compose up -d

  build.up:
    cmd: docker compose up -d --build

  seed:
    cmds:
      - docker compose exec $CONTAINER_NAME wrangler d1 execute $DB_NAME --file=./sql/schema.sql
      - docker compose exec $CONTAINER_NAME wrangler d1 migrations apply $DB_NAME

  seed.local:
    cmds:
      - docker compose down --rmi all --volumes --remove-orphans

  lint:
    cmds:
      - docker compose run --rm  api go fmt ./...
      - docker compose run --rm  api go vet ./...
      - docker compose run --rm  api go mod tidy
      - gci write --skip-generated -s standard -s default ./src
