DROP TABLE IF EXISTS Whiskys;
CREATE TABLE Whiskys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  volume INTEGER,
  abv INTEGER,
	kind TEXT,
	area TEXT,
  company TEXT,
  description TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS HealthCheck;
CREATE TABLE HealthCheck (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
	connection TEXT NOT NULL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO HealthCheck(connection) VALUES('ok');
