name: ci

on:
  pull_request:
  merge_group:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Run Prettier
        run: |
          npm install
          npx prettier --write ${FILE_PATTERN}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier Change

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: "src/**/*.{ts,tsx}"
          fail_on_error: true # 指摘が発生したらjobを失敗させる

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            ./**/*.{ts,tsx,js,jsx,json}
